[package]
name = "app-backups"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.0.15", features = ["derive"] }
directories = "5.0.1"
eframe = "0.22.0"
walkdir = "2.3.3"
wo-common = { version = "0.1.0", path = "../../crates/wo-common" }
