[package]
name = "app-keybindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
eframe = "0.22.0"
wo-common = { version = "0.1.0", path = "../../crates/wo-common" }
